export interface EmojiItem {
  char: string
  keywords: string
}

export interface EmojiCategory {
  id: string
  icon: string
  emojis: EmojiItem[]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    icon: 'mood',
    emojis: [
      { char: '😀', keywords: 'sonrisa feliz smile happy grin' },
      { char: '😃', keywords: 'sonrisa feliz smile happy' },
      { char: '😄', keywords: 'sonrisa feliz smile happy laugh' },
      { char: '😁', keywords: 'sonrisa feliz grin happy' },
      { char: '😆', keywords: 'risa laugh happy jaja' },
      { char: '😅', keywords: 'risa nervioso sweat smile' },
      { char: '🤣', keywords: 'risa carcajada rofl lol' },
      { char: '😂', keywords: 'risa llanto lol joy jaja' },
      { char: '🙂', keywords: 'sonrisa smile' },
      { char: '🙃', keywords: 'sonrisa invertida upside down' },
      { char: '😉', keywords: 'guino wink' },
      { char: '😊', keywords: 'sonrisa feliz blush happy' },
      { char: '😇', keywords: 'angel inocente halo' },
      { char: '🥰', keywords: 'amor cariño love hearts' },
      { char: '😍', keywords: 'enamorado amor love heart eyes' },
      { char: '🤩', keywords: 'sorpresa estrellas star struck' },
      { char: '😘', keywords: 'beso kiss love' },
      { char: '😗', keywords: 'beso kiss' },
      { char: '😚', keywords: 'beso kiss' },
      { char: '😙', keywords: 'beso kiss' },
      { char: '😋', keywords: 'rico delicioso yum sabroso' },
      { char: '😛', keywords: 'lengua tongue' },
      { char: '😜', keywords: 'guino lengua wink tongue' },
      { char: '🤪', keywords: 'loco crazy zany' },
      { char: '😝', keywords: 'lengua tongue' },
      { char: '🤑', keywords: 'dinero money' },
      { char: '🤗', keywords: 'abrazo hug' },
      { char: '🤭', keywords: 'risa vergüenza giggle' },
      { char: '🤫', keywords: 'silencio shh quiet' },
      { char: '🤔', keywords: 'pensando thinking duda' },
      { char: '😐', keywords: 'neutral' },
      { char: '😑', keywords: 'sin expresion expressionless' },
      { char: '😶', keywords: 'sin palabras no mouth' },
      { char: '😏', keywords: 'sonrisa picara smirk' },
      { char: '😒', keywords: 'fastidio unamused' },
      { char: '🙄', keywords: 'ojos en blanco eyeroll' },
      { char: '😬', keywords: 'nervioso grimace' },
      { char: '🤥', keywords: 'mentira lying pinocho' },
    ],
  },
  {
    id: 'gestures',
    icon: 'back_hand',
    emojis: [
      { char: '👍', keywords: 'bien like ok pulgar' },
      { char: '👎', keywords: 'mal dislike' },
      { char: '👌', keywords: 'ok perfecto' },
      { char: '🤌', keywords: 'italiano pinch' },
      { char: '✌️', keywords: 'paz peace victoria' },
      { char: '🤞', keywords: 'suerte cruzar dedos luck' },
      { char: '🤟', keywords: 'amor love you' },
      { char: '🤘', keywords: 'rock' },
      { char: '👊', keywords: 'puño punch fist' },
      { char: '✊', keywords: 'puño fist' },
      { char: '🤛', keywords: 'puño izquierda fist' },
      { char: '🤜', keywords: 'puño derecha fist' },
      { char: '👏', keywords: 'aplausos clap' },
      { char: '🙌', keywords: 'celebracion praise hands' },
      { char: '👐', keywords: 'manos abiertas open hands' },
      { char: '🤲', keywords: 'manos juntas palms' },
      { char: '🙏', keywords: 'gracias please pray oracion' },
      { char: '🤝', keywords: 'trato handshake acuerdo' },
      { char: '💪', keywords: 'fuerza muscle flex' },
      { char: '👋', keywords: 'hola adios wave saludo' },
      { char: '🖐️', keywords: 'mano hand' },
      { char: '✋', keywords: 'alto stop mano' },
      { char: '👆', keywords: 'arriba point up' },
      { char: '👇', keywords: 'abajo point down' },
      { char: '👈', keywords: 'izquierda point left' },
      { char: '👉', keywords: 'derecha point right' },
      { char: '☝️', keywords: 'arriba index up' },
    ],
  },
  {
    id: 'hearts',
    icon: 'favorite',
    emojis: [
      { char: '❤️', keywords: 'amor corazon love heart' },
      { char: '🧡', keywords: 'corazon naranja orange heart' },
      { char: '💛', keywords: 'corazon amarillo yellow heart' },
      { char: '💚', keywords: 'corazon verde green heart' },
      { char: '💙', keywords: 'corazon azul blue heart' },
      { char: '💜', keywords: 'corazon morado purple heart' },
      { char: '🖤', keywords: 'corazon negro black heart' },
      { char: '🤍', keywords: 'corazon blanco white heart' },
      { char: '🤎', keywords: 'corazon marron brown heart' },
      { char: '💔', keywords: 'corazon roto broken heart' },
      { char: '❣️', keywords: 'corazon exclamacion heart' },
      { char: '💕', keywords: 'corazones love two hearts' },
      { char: '💞', keywords: 'corazones giratorios revolving' },
      { char: '💓', keywords: 'corazon latiendo beating' },
      { char: '💗', keywords: 'corazon creciendo growing' },
      { char: '💖', keywords: 'corazon brillante sparkling' },
      { char: '💘', keywords: 'corazon flecha cupido cupid' },
      { char: '💝', keywords: 'corazon regalo gift heart' },
    ],
  },
  {
    id: 'animals',
    icon: 'pets',
    emojis: [
      { char: '🐶', keywords: 'perro dog' },
      { char: '🐱', keywords: 'gato cat' },
      { char: '🐭', keywords: 'raton mouse' },
      { char: '🐹', keywords: 'hamster' },
      { char: '🐰', keywords: 'conejo rabbit' },
      { char: '🦊', keywords: 'zorro fox' },
      { char: '🐻', keywords: 'oso bear' },
      { char: '🐼', keywords: 'panda' },
      { char: '🐨', keywords: 'koala' },
      { char: '🐯', keywords: 'tigre tiger' },
      { char: '🦁', keywords: 'leon lion' },
      { char: '🐮', keywords: 'vaca cow' },
      { char: '🐷', keywords: 'cerdo pig' },
      { char: '🐸', keywords: 'rana frog' },
      { char: '🐵', keywords: 'mono monkey' },
      { char: '🐔', keywords: 'gallina chicken' },
      { char: '🐧', keywords: 'pinguino penguin' },
      { char: '🐦', keywords: 'pajaro bird' },
      { char: '🦄', keywords: 'unicornio unicorn' },
      { char: '🐴', keywords: 'caballo horse' },
      { char: '🐺', keywords: 'lobo wolf' },
      { char: '🐢', keywords: 'tortuga turtle' },
      { char: '🐬', keywords: 'delfin dolphin' },
      { char: '🐳', keywords: 'ballena whale' },
    ],
  },
  {
    id: 'food',
    icon: 'restaurant',
    emojis: [
      { char: '🍎', keywords: 'manzana apple' },
      { char: '🍌', keywords: 'banana platano' },
      { char: '🍕', keywords: 'pizza' },
      { char: '🍔', keywords: 'hamburguesa burger' },
      { char: '🍟', keywords: 'papas fritas fries' },
      { char: '🌮', keywords: 'taco' },
      { char: '🍣', keywords: 'sushi' },
      { char: '🍦', keywords: 'helado ice cream' },
      { char: '🍩', keywords: 'donut' },
      { char: '🍪', keywords: 'galleta cookie' },
      { char: '🍰', keywords: 'pastel cake' },
      { char: '🎂', keywords: 'cumpleaños birthday cake' },
      { char: '🍫', keywords: 'chocolate' },
      { char: '🍿', keywords: 'palomitas popcorn' },
      { char: '☕', keywords: 'cafe coffee' },
      { char: '🍺', keywords: 'cerveza beer' },
      { char: '🍷', keywords: 'vino wine' },
      { char: '🥤', keywords: 'bebida soda drink' },
    ],
  },
  {
    id: 'activities',
    icon: 'sports_soccer',
    emojis: [
      { char: '⚽', keywords: 'futbol soccer' },
      { char: '🏀', keywords: 'basquetbol basketball' },
      { char: '🏈', keywords: 'futbol americano football' },
      { char: '⚾', keywords: 'beisbol baseball' },
      { char: '🎾', keywords: 'tenis tennis' },
      { char: '🏆', keywords: 'trofeo trophy' },
      { char: '🎮', keywords: 'videojuego game controller' },
      { char: '🎲', keywords: 'dado dice' },
      { char: '🎸', keywords: 'guitarra guitar' },
      { char: '🎧', keywords: 'audifonos headphones musica' },
      { char: '🎤', keywords: 'microfono mic canto' },
      { char: '🎬', keywords: 'pelicula movie' },
      { char: '📚', keywords: 'libros books' },
      { char: '✈️', keywords: 'avion airplane viaje' },
      { char: '🚗', keywords: 'carro auto car' },
      { char: '🎉', keywords: 'fiesta celebracion party' },
      { char: '🎁', keywords: 'regalo gift' },
      { char: '🔥', keywords: 'fuego fire genial' },
    ],
  },
  {
    id: 'objects',
    icon: 'lightbulb',
    emojis: [
      { char: '💡', keywords: 'idea bombilla lightbulb' },
      { char: '📱', keywords: 'celular telefono phone' },
      { char: '💻', keywords: 'computadora laptop' },
      { char: '⌚', keywords: 'reloj watch' },
      { char: '📷', keywords: 'camara camera' },
      { char: '🔑', keywords: 'llave key' },
      { char: '🔒', keywords: 'candado lock' },
      { char: '💰', keywords: 'dinero money' },
      { char: '💳', keywords: 'tarjeta card' },
      { char: '📌', keywords: 'pin pushpin' },
      { char: '📝', keywords: 'nota memo escribir' },
      { char: '✅', keywords: 'listo check ok hecho' },
      { char: '❌', keywords: 'no cruz cross error' },
      { char: '⭐', keywords: 'estrella star' },
      { char: '⚡', keywords: 'rayo lightning' },
      { char: '⏰', keywords: 'alarma reloj clock' },
    ],
  },
  {
    id: 'symbols',
    icon: 'emoji_symbols',
    emojis: [
      { char: '💯', keywords: 'cien cien por ciento perfect' },
      { char: '❗', keywords: 'exclamacion importante' },
      { char: '❓', keywords: 'pregunta duda question' },
      { char: '💭', keywords: 'pensamiento thought bubble' },
      { char: '💤', keywords: 'dormir sleep zzz' },
      { char: '♻️', keywords: 'reciclar recycle' },
      { char: '🆗', keywords: 'ok' },
      { char: '🔴', keywords: 'circulo rojo red' },
      { char: '🟢', keywords: 'circulo verde green' },
      { char: '🟡', keywords: 'circulo amarillo yellow' },
      { char: '⚠️', keywords: 'advertencia warning' },
      { char: '🚫', keywords: 'prohibido no permitido' },
    ],
  },
]
